/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.figuras;

/**
 *
 * @author Wesly
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    VentanaCirculo objCirculo = new VentanaCirculo();
    
    private void inicializarFormularios(){
        VentanaCirculo.setContentPane(objCirculo);
    }
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        VentanaCirculo = new javax.swing.JInternalFrame();
        VentanaCuadrado = new javax.swing.JInternalFrame();
        VentanaRectangulo = new javax.swing.JInternalFrame();
        VentanaTrianguloRectangulo = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jmiCirculo = new javax.swing.JMenuItem();
        jmiCuadrado = new javax.swing.JMenuItem();
        jmiRectangulo = new javax.swing.JMenuItem();
        jmiTrianguloRectangulo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaCirculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        VentanaCirculo.setVisible(false);

        javax.swing.GroupLayout VentanaCirculoLayout = new javax.swing.GroupLayout(VentanaCirculo.getContentPane());
        VentanaCirculo.getContentPane().setLayout(VentanaCirculoLayout);
        VentanaCirculoLayout.setHorizontalGroup(
            VentanaCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        VentanaCirculoLayout.setVerticalGroup(
            VentanaCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 124, Short.MAX_VALUE)
        );

        desktopPane.add(VentanaCirculo);
        VentanaCirculo.setBounds(50, 40, 200, 160);

        VentanaCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        VentanaCuadrado.setVisible(false);

        javax.swing.GroupLayout VentanaCuadradoLayout = new javax.swing.GroupLayout(VentanaCuadrado.getContentPane());
        VentanaCuadrado.getContentPane().setLayout(VentanaCuadradoLayout);
        VentanaCuadradoLayout.setHorizontalGroup(
            VentanaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        VentanaCuadradoLayout.setVerticalGroup(
            VentanaCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        desktopPane.add(VentanaCuadrado);
        VentanaCuadrado.setBounds(20, 10, 200, 190);

        VentanaRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        VentanaRectangulo.setVisible(false);

        javax.swing.GroupLayout VentanaRectanguloLayout = new javax.swing.GroupLayout(VentanaRectangulo.getContentPane());
        VentanaRectangulo.getContentPane().setLayout(VentanaRectanguloLayout);
        VentanaRectanguloLayout.setHorizontalGroup(
            VentanaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        VentanaRectanguloLayout.setVerticalGroup(
            VentanaRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(VentanaRectangulo);
        VentanaRectangulo.setBounds(50, 10, 200, 160);

        VentanaTrianguloRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        VentanaTrianguloRectangulo.setVisible(false);

        javax.swing.GroupLayout VentanaTrianguloRectanguloLayout = new javax.swing.GroupLayout(VentanaTrianguloRectangulo.getContentPane());
        VentanaTrianguloRectangulo.getContentPane().setLayout(VentanaTrianguloRectanguloLayout);
        VentanaTrianguloRectanguloLayout.setHorizontalGroup(
            VentanaTrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        VentanaTrianguloRectanguloLayout.setVerticalGroup(
            VentanaTrianguloRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(VentanaTrianguloRectangulo);
        VentanaTrianguloRectangulo.setBounds(50, 0, 200, 160);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Figuras");

        jmiCirculo.setMnemonic('o');
        jmiCirculo.setText("Circulo");
        jmiCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCirculoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCirculo);

        jmiCuadrado.setMnemonic('s');
        jmiCuadrado.setText("Cuadrado");
        jmiCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCuadradoActionPerformed(evt);
            }
        });
        fileMenu.add(jmiCuadrado);

        jmiRectangulo.setMnemonic('a');
        jmiRectangulo.setText("Rectangulo");
        jmiRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiRectangulo);

        jmiTrianguloRectangulo.setMnemonic('x');
        jmiTrianguloRectangulo.setText("Triangulo Rectangulo");
        jmiTrianguloRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTrianguloRectanguloActionPerformed(evt);
            }
        });
        fileMenu.add(jmiTrianguloRectangulo);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiTrianguloRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTrianguloRectanguloActionPerformed
        VentanaTrianguloRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiTrianguloRectanguloActionPerformed

    private void jmiRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRectanguloActionPerformed
        // TODO add your handling code here:
        VentanaRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiRectanguloActionPerformed

    private void jmiCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCirculoActionPerformed
        // TODO add your handling code here:
        VentanaCirculo.setVisible(true);
    }//GEN-LAST:event_jmiCirculoActionPerformed

    private void jmiCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCuadradoActionPerformed
        // TODO add your handling code here:
        VentanaCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiCuadradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame VentanaCirculo;
    private javax.swing.JInternalFrame VentanaCuadrado;
    private javax.swing.JInternalFrame VentanaRectangulo;
    private javax.swing.JInternalFrame VentanaTrianguloRectangulo;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jmiCirculo;
    private javax.swing.JMenuItem jmiCuadrado;
    private javax.swing.JMenuItem jmiRectangulo;
    private javax.swing.JMenuItem jmiTrianguloRectangulo;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
